from pathlib import Path
ROUTER=Path('app/routers/kwealth.py')
def main():
    if not ROUTER.exists(): raise SystemExit(f'Missing {ROUTER}. Run from repository root.')
    s=ROUTER.read_text(encoding='utf-8')
    marker='@router.get("/member/kwealth/books", response_class=HTMLResponse)\n'
    if '@router.get("/member/kwealth/books/reading-room", response_class=HTMLResponse)' not in s:
        route='''@router.get("/member/kwealth/books/reading-room", response_class=HTMLResponse)\nasync def kwealth_reading_room(\n    request: Request,\n    book_id: Optional[int] = None,\n    user: User = Depends(require_user),\n    session: Session = Depends(get_session),\n):\n    if not book_id:\n        return RedirectResponse("/member/kwealth/books", status_code=303)\n    book = session.get(KwealthBook, book_id)\n    if not book or not getattr(book, "is_active", True):\n        return RedirectResponse("/member/kwealth/books", status_code=303)\n    own = getattr(book, "owner_user_id", None)\n    if own is not None and int(own) != int(user.id):\n        return RedirectResponse("/member/kwealth/books", status_code=303)\n    text = _load_book_text(book)\n    pages = _split_pages(text)\n    page_index = 0\n    prog = session.exec(select(KwealthProgress).where(KwealthProgress.user_id == user.id, KwealthProgress.book_id == book.id)).first()\n    if prog and pages:\n        page_index = max(0, min(prog.page_index, len(pages) - 1))\n    return templates.TemplateResponse("kwealth/reading_room.html", {\n        "request": request, "user": user, "book": book, "pages": pages,\n        "page_index": page_index, "mh_url": MH_URL,\n    })\n\n'''
        if marker not in s: raise SystemExit('Books route marker not found')
        s=s.replace(marker,route+marker,1)
    start=s.find('@router.post("/member/kwealth/books/upload")'); end=s.find('@router.post("/member/kwealth/books/progress")',start)
    if start<0 or end<0: raise SystemExit('Upload route boundaries not found')
    upload='''@router.post("/member/kwealth/books/upload")\nasync def kwealth_books_upload(\n    files: List[UploadFile] = File(...),\n    user: User = Depends(require_user),\n    session: Session = Depends(get_session),\n):\n    existing = session.exec(select(KwealthBook).where(KwealthBook.is_active == True, KwealthBook.owner_user_id == user.id)).all()\n    if len(existing) >= 3:\n        return RedirectResponse("/member/kwealth/books?upload_limit=3", status_code=303)\n    count = 0\n    allowed = {".pdf", ".txt", ".docx"}\n    for f in files or []:\n        if len(existing) + count >= 3: break\n        ext=Path((f.filename or "").lower()).suffix\n        if ext not in allowed: continue\n        raw=await f.read()\n        if not raw or len(raw) > 4_000_000: continue\n        try: text=_extract_text_from_upload(raw, f.filename or "book.txt")\n        except FormatConvertError: return RedirectResponse("/member/kwealth/books?convert=fail", status_code=303)\n        except Exception: return RedirectResponse("/member/kwealth/books?convert=fail", status_code=303)\n        text=(text or "").strip()\n        if len(text)<20: return RedirectResponse("/member/kwealth/books?convert=fail", status_code=303)\n        safe=f"u{user.id}_{uuid.uuid4().hex[:10]}.txt"\n        dest=Path(__file__).resolve().parent.parent/"static"/"uploads"/"kwealth_books_text"/safe\n        dest.parent.mkdir(parents=True,exist_ok=True); dest.write_text(text,encoding="utf-8")\n        title=(f.filename or "Book").rsplit(".",1)[0][:180]\n        book=KwealthBook(title=title,author=None,source_path=str(dest),page_count=len(_split_pages(text)),is_active=True,owner_user_id=user.id)\n        session.add(book); session.commit(); session.refresh(book)\n        session.add(KwealthProgress(user_id=user.id,book_id=book.id,page_index=0)); session.commit(); count+=1\n    return RedirectResponse(f"/member/kwealth/books?uploaded={count}", status_code=303)\n\n'''
    s=s[:start]+upload+s[end:]
    ROUTER.write_text(s,encoding='utf-8'); print('Applied reading-room backend fix')
if __name__=='__main__': main()
